### ISSUE TITLE
Cannot install Splat 2.0 on PCL Projects

### ISSUE THREAD

**Issue by Corjuh** [paulcbetts/splat#149]
I have a solution for an Android and iOS app that has a number of PCL projects. Some of the PCL projects have Splat 1.6.2 installed for things like logging, but I am unable to upgrade to 2.0. The error message I get in the package console is:

```
Could not install package 'Splat 2.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

I am using:
macOS 10.12.1
Xamarin Studio 6.1.2

**Comment by sendajob** [comment]
I am having the same issue, any solutions?

**Comment by mark-larter** [comment]
I am too. It might be related to this issue, [](https://github.com/dotnet/roslyn/issues/11067).

Although the issue was closed, there are very recent comments in the thread that refer to the issue resurfacing with VS2017.

We ran into the issue under VS2015, did the workaround and had this working in app at current client, then it broke again after the most recent round of Xamarin updates.

**Comment by poseydonfba** [comment]
I can only install version 2.0.0 on profile111

**Comment by PaulSinnema** [comment]
Did anyone solve this one?

**Comment by ghuntley** [comment]
Please use Splat `1.6.2` when targeting PCL projects. v2.0 and onwards is `netstandard` only. There will be no updates to the `1.6.x` series so if you need to patch the release then please fork and maintain your own copy/build from source.
